### ISSUE TITLE
Update for L5

### ISSUE THREAD

**Issue by JayBizzle** [ipunkt/laravel-analytics#10]
Any plans to update this to work with Laravel 5?

**Comment by rokde** [comment]
Good question. I try in about an hour to accomplish this update.

**Comment by rokde** [comment]
Laravel 5 is now supported since Tag 1.1.0 (https://github.com/ipunkt/laravel-analytics/tree/1.1.0)

**Comment by JayBizzle** [comment]
Brilliant :+1:

**Comment by rokde** [comment]
Thanx a lot ;) Not easy, but now the package can handle laravel 4 and 5. This is very cool I think.
