### ISSUE TITLE
Call to undefined method: Ipunkt\LaravelAnalytics\AnalyticsFacade::render()

### ISSUE THREAD

**Issue by andygold99** [ipunkt/laravel-analytics#12]
I am getting this error when I add the ```{{ Analytics::render() }}``` code to my blade. Is there a problem with the repo?

Thanks

Andy

**Comment by rokde** [comment]
Do you have added the Service Provider?

**Comment by andygold99** [comment]
Thanks I missed that bit in the instructions. Works now :)

**Comment by rokde** [comment]
Okay, maybe I can write it more prominent.
