### ISSUE TITLE
Event lost on multiple redirects

### ISSUE THREAD

**Issue by maarten00** [ipunkt/laravel-analytics#14]
I have set up my controller to send an event on login: 
`if (Auth::attempt($user)){`
    `    Analytics::trackCustom(SettingsHelper::AnalyticsFormatter(Auth::user(), "login", Auth::user()->id,     Auth::user()->id));`
			`    return Redirect::intended('/');`
        `}`
This works fine for me. The correct event is being printed when calling `Analytics::render()` in my (master)view. 

However, there is an extra bit of code being executed on the "/" URL: 
`//salesman redirect to calculator`
        `if (Auth::user()->hasRole('Salesman') )`
                    `return Redirect::to('calculator');`
So basically, after logging in and no intended URL was entered, you get redirected to the page '/'. However, that page is not accessible for salesmen, so they get redirected to the calculator page. After that the page is being rendered with a `Analytics::render` call. There have been no calls to this function in between, so my event was never rendered on any inbetween pages. However when I arrive on the 'calculator' page, the event is not there. It never gets triggered for salesmen.

In the meantime I have implemented a workaround, but ideally it would be possible to remember this event over multiple requests if it was never rendered. I can understand that there are use cases where this is not the desired behavior, so it would probably be best to enable this behavior through the config.

**Comment by rokde** [comment]
Internally we store the data with Session::flash() so you have only one hop. Maybe you can implement your own TrackingBag with https://github.com/ipunkt/laravel-analytics/blob/master/src/Ipunkt/LaravelAnalytics/TrackingBag.php#L31 Session::put($this->sessionIdentifier, $sessionTracks)

Or you re-track the tracking information.

Is it a solution for you to call "Analytics::rememberForRedirect()" or some call like this before you redirect again?

**Comment by maarten00** [comment]
I'd prefer using another tracking bag which permanently stores it in session until it is displayed. I'll whip something up when I get some free time and create a pull request. Thanks for the suggestion!

**Comment by rokde** [comment]
Yes, do the pull request if you have something done.
