### ISSUE TITLE
Analytic Config Per Enviroment 

### ISSUE THREAD

**Issue by eknowlton** [ipunkt/laravel-analytics#15]
Thanks for your time developing this Adapter, great work!

I may be wrong, but it seems that I can't provide a analytic config file per enviroment.
I've only tested this in Laravel 4.2.

I've setup the following below...

`app/config/packages/ipunkt/laravel-analytics/macdev/analytics.php`

Which I thought would overwrite `app/config/packages/ipunkt/laravel-analytics/analytics.php`, but it doesn't seem too.

Any think this can happen in the future, or am I just doing it wrong.

**Comment by justb81** [comment]
you can divide your config by environment by inserting paths under the package config:

`app/config/packages/ipunkt/laravel-analytics/local/analytics.php`
`app/config/packages/ipunkt/laravel-analytics/staging/analytics.php`
`app/config/packages/ipunkt/laravel-analytics/production/analytics.php`

if you have a "global" package config: `app/config/packages/ipunkt/laravel-analytics/analytics.php` this is overridden by your environment-config.

does that solve your issue?

**Comment by rokde** [comment]
We close that issue by unanswered solution.
