### ISSUE TITLE
This Package is support Laravel5?

### ISSUE THREAD

**Issue by ALTELMA** [ipunkt/laravel-analytics#21]
I spent many hour to install package. when I put config will get an error Array_merge() on serviceProvider 

I try to clear-compiled still doesn't work. please give me for more information to use it.
Thanks a lot.

**Comment by ALTELMA** [comment]
A problem come from
$this->mergeConfigFrom($config, 'analytics');

Could you check it and fix?

**Comment by rokde** [comment]
What laravel version do you have and which package version do you include?

**Comment by islalobo** [comment]
We're using version 5.1.27 (LTS) and including package version "ipunkt/laravel-analytics": "~2.0" and facing the same issue.

**Comment by rokde** [comment]
http://laravel.com/docs/5.1/packages -  like expected. I don't know what the problem is.

**Comment by ALTELMA** [comment]
The problem cause from config file. If you already config before won't get any error, but if you try to manually create config without use vendor:publish get an error too.

I don't know why it's work for you. Try to install L5 and get your latest package. Maybe you'll facing problem like me.

I hope you'll find that error :dart:

**Comment by rokde** [comment]
This behaviour is not reproducible for me. A lot of other packages do their configuration the same way without having any trouble.
