### ISSUE TITLE
htmlentities

### ISSUE THREAD

**Issue by Guillawme** [ipunkt/laravel-analytics#23]
In Laravel 5, should we not rather use {!! Analytics::render() !!} instead of {{ Analytics::render() }} to avoid htmlentities function? 
(reference: http://laravel.com/docs/5.1/blade#displaying-data > Displaying Unescaped Data)

**Comment by Nrohtgnohp** [comment]
I think many detail still base on Laravel 4.0

**Comment by ALTELMA** [comment]
I think many detail still base on Laravel 4.0
