### ISSUE TITLE
Composer Failure : Package could not be found.

### ISSUE THREAD

**Issue by mikehenken** [ipunkt/laravel-analytics#24]
I am receiving errors when attempting to run composer install. I took the require line out of documentation.
"The requested package ipunkt/laravel-analytics could not be found in any version"

**Comment by murrion** [comment]
Happened to me too, try changing the following in composer.json

From: 
 "ipunkt/laravel-analytics": "~2.0"

to:
 "ipunkt/laravel-analytics": "1.1.4"

**Comment by rokde** [comment]
It has to be "ipunkt/laravel-analytics": "~1.0".
