### ISSUE TITLE
Readme for L4

### ISSUE THREAD

**Issue by mikehenken** [ipunkt/laravel-analytics#25]
For L4 there is no "php artisan vendor" for publishing config. Might make sense to put command for L4/L5 separately.
"php artisan config:publish ipunkt/laravel-analytics" still works fine for L4.

**Comment by rokde** [comment]
You can do `php artisan vendor:publish --provider="Ipunkt\LaravelAnalytics\AnalyticsServiceProvider"` to publish the config file in Laravel 5. So nothing to do here.
