### ISSUE TITLE
Allow setting other settings via .env as well

### ISSUE THREAD

**Issue by martijn94** [ipunkt/laravel-analytics#33]
Currently only the TrackingID and Proviver can be set via a .env variable.

 It would be nice if that would also be possible for the other settings.

**Comment by rokde** [comment]
Tracking ID setting should not change in live code. And Provider is the basis for creation in Service Provider. So when you need a different provider simply use your own provider to instantiate or add a factory or manager pattern on your own.
We will not implement this behaviour. Sorry.

**Comment by martijn94** [comment]
Hi Robert,

I think you misunderstood my question. Currently the only settings that can be set via .env are ANALYTICS_TRACKING_ID and ANALYTICS_PROVIDER.

I would love to see the ability to set display_features, anonymize_ip, auto_track and debug options via .env as well.

**Comment by rokde** [comment]
Okay, I misunderstood you, that's right.

**Comment by WaveHack** [comment]
This should be fixed by now due to PR https://github.com/ipunkt/laravel-analytics/pull/39

**Comment by rokde** [comment]
Release 1.3.2 solves this issue.
