### ISSUE TITLE
NoAnalytics::TrackEvent() failing when 3rd arg not present - even though it is null

### ISSUE THREAD

**Issue by SturmDrangAltaar** [ipunkt/laravel-analytics#44]
Exception trace:
`
ErrorException in NoAnalytics.php line 49:
Missing argument 3 for Ipunkt\LaravelAnalytics\Providers\NoAnalytics::trackEvent()
`

**Current function:**
`
/**
     * track an event
     *
     * @param string $category
     * @param string $action
     * @param null|string $label
     * @param null|int $value
     *
     * @return void
     */
    public function trackEvent($category, $action, $label, $value)
    {
    }

`

**According to the phpdoc here, this should then be:**
`
/**
     * track an event
     *
     * @param string $category
     * @param string $action
     * @param null|string $label
     * @param null|int $value
     *
     * @return void
     */
    public function trackEvent($category, $action, $label = null, $value = null)
    {
    }

`

**Comment by rokde** [comment]
This is fixed with version 1.3.5

**Comment by SturmDrangAltaar** [comment]
@rokde Apologies, didn't realise I was running an older version on my local env. Thanks for the great work!
