### ISSUE TITLE
how to use google oauth to access view id ?

### ISSUE THREAD

**Issue by saeedvir** [ipunkt/laravel-analytics#46]
how to use google oauth to access view id ?

my website --> user login with google analytics account (OAUTH 2) --> get user google analytics view id --> report ( for ex: get pageviews)

**Comment by rokde** [comment]
I do not know what you exactly mean. Do you have a link for me for the manual providing this feature for analytics? If you can set it as an option for the javascript we have a method for this. But I think you want something different.
