### ISSUE TITLE
disable via config

### ISSUE THREAD

**Issue by lsmith77** [ipunkt/laravel-analytics#57]
I would like to disable GA tracking in feature branches.

I am using platform.sh for hosting where I can deploy every feature branch and there I can set env variables for each deployment. For staging I will use a different tracking ID but for feature branches this isn't really feasible or sensible.

So I basically still want any method call to work but it should not add the GA javascript and any call to the PHP API should not communicate with GA.

Would you be open to a PR that implements?

I would basically add a `disabled` key to the configuration

**Comment by rokde** [comment]
This is already implemented. Just set `ANALYTICS_PROVIDER` in your environment or `analytics.provider` config entry to `NoAnalytics` and you are done.

The NoAnalytics Provider is a Null-Pattern implementation, so everything works fine - like in tests useful.

**Comment by lsmith77** [comment]
thx!
