### ISSUE TITLE
Compatibility with Analytics v4 

### ISSUE THREAD

**Issue by aroy314** [ipunkt/laravel-analytics#64]
As you may have seen, Analytics has a new version and the ID given doesn't look like the `UA-000000000-1`. 

When I create a new website on Analytics, I have an ID like `G-XXXXXXXXXX` and a "Flux ID" that looks like `000000000`. 
Could you please confirm your package is / will be compatible with these identifiers ? 
And which one of these two ID should I use ?
I guess your README should also be updated for that.

Thanks !

**Comment by rokde** [comment]
This seems to be a greater change. We are not able to support such an intense of work right now. Maybe you can do it yourself and make a PR - or you should look for another package.

Hope that answer helps.
