### ISSUE TITLE
php8 support

### ISSUE THREAD

**Issue by 2618094** [ipunkt/laravel-analytics#67]
Please add php8 support to your composer.json
I not made PR because it's may cause side effects :)

**Comment by rokde** [comment]
can you check dev-master?

**Comment by 2618094** [comment]
Yep, dev-master can be installed on php8 :)
But i did't checked functional well.

**Comment by rokde** [comment]
Then I build a new version with php-8 support.

**Comment by 2618094** [comment]
Thx, working 👍
