### ISSUE TITLE
Analytics::trackCustom Method Builds Up with Session

### ISSUE THREAD

**Issue by javalight** [ipunkt/laravel-analytics#9]
Every Time i Call this method in my controller it adds the string to the end of the script. 

ex: 
Controller:
   Analytics::trackCustom("ga('set', 'dimension1', $user->id);");

View Script:
...
ga('create', 'UA-xxxxxxxx-1', 'auto');
ga('set', 'anonymizeIp', true);
ga('set', 'dimension1', 42); // 2 times!!! 
ga('set', 'dimension1', 42); // 2 times!!!
ga('send', 'pageview');

Every Time my controller runs the method 'Analytics::trackCustom' it adds another copy of the string to the end of the script. I would like it to only show 1 copy of it? Unless this is a feature and im missing something? In the TrackingBag Class if i remove line 33 everything seems to work.

**Comment by rokde** [comment]
Can you try the updated code? I can not reproduce your misbehaviour. So then it is good, I tag this as new release.
Please add dev-master as version constraint in composer for verifying the fix.

**Comment by javalight** [comment]
Yes this seems to have fixed the error, duplicates do not appear anymore. But if i load the controller and the string changes in the Analytics::trackCustom method or the Analytics::trackEvent method, the old string and the new string append to the end of the script. I dont understand why the old string is there it seems to be cached in the session ?

**Comment by rokde** [comment]
Can you paste your source code please?

**Comment by pierrerigal** [comment]
I have the same problem. I want to track the area of the visitor.

This is how to reproduce it : 

In BaseController.php
````php
Analytics::trackCustom("ga('set', 'dimension1', ".Session::get('my_area.slug').");");
````

With a clean (private mode on chrome) browser :

1) Hit a page http://www.domain.com/area/new-york, in html output :
````js
ga('create', 'UA-********', 'auto');
ga('set', 'dimension1', new-york);
ga('send', 'pageview');
````
-> OK

2) Hit a second page http://www.domain.com/area/new-york/events, in html output :
````js
ga('create', 'UA-********', 'auto');
ga('set', 'dimension1', new-york);
ga('send', 'pageview');
````
-> OK

3) Hit a third page, change area : http://www.domain.com/area/chicago, in html output :
````js
ga('create', 'UA-********', 'auto');
ga('set', 'dimension1', new-york);
ga('set', 'dimension1', chicago);
ga('send', 'pageview');
````
-> NOK
Chicago should be there but no longuer new-york. (I'm on dev-master).

**Comment by rokde** [comment]
I think I know the problem. Let me try to dive into deeper today.

**Comment by rokde** [comment]
The commit c977fd6644adf73ff714d11f81f71fdb45749f78 should solve the problem. Can you test it?

**Comment by pierrerigal** [comment]
Solved :)

Thx.
